version: '3'
services:
  app:
    build: ./docker/node
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    networks:
      - exterior
      - db

  mongodb:
    image: mongo:bionic
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - db
      - exterior

networks:
  db:
    internal: true
  exterior:
    internal: false

volumes:
  data: {}
